### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by ColonelGerdauf**
Used a suggestion and extended it to boxed sub-headers where colours are supposed to display. Now that I am aware that there is indeed a simple solution to my original problem, I would like to have the fix extended to another location which could benefit from such solution.

### CODE REVIEW

**Comment by the-j0k3r** [comment]
#181 is already fixed and fix committed.

**Comment by ColonelGerdauf** [comment]
Thank you, but I have added an additional area, that appears to also fix things for another section that was not previously displaying as intended

Sorry about that, The original commit was that same one you noted issues with, the next one brought your 181 fix, and the last was my own tweak

**Comment by the-j0k3r** [comment]
> Sorry about that, The original commit was that same one you noted issues with, the next one brought your 181 fix, and the last was my own tweak

This wont work, because the fix for #181 you added is conflicting with the existing and thus causes conflicts.

Capture

also such tweak you added all though it looks harmless please link URL and explain what it fixes.

You will need to start with a clean PR though as I dont have access to a dev environment, only via web on a clunky interface.

Ill close this sorry, and hope a clean PR with explanation comes along.

Thx

**Comment by ColonelGerdauf** [comment]
Thank you. I am on it

**Pull request closed without merging**
