### PR TITLE
Add background color for user message pop-ups

### PR DESCRIPTION
**Pull request by HerrHulaHoop**
Message notifications that show up as a banner in the wiki page does not have a background making it pretty easy to miss. Added a background to let it stand out.

Original white theme
white

Before
before

After
after

Let me know if you have any comments!

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @HerrHulaHoop!

I don't think green is the right color for those popups. Either pick brown, a darker version of the original yellow, or grey.

**Comment by HerrHulaHoop** [comment]
Changed it to grey. Opted for grey as brown didn't stand out enough and yellow made it difficult to read the text.

image

Let me know if this is okay!

**Comment by HerrHulaHoop** [comment]
`#333` seems like a better fit as `#282828` looks is a bit too dark. The notification has to have a little contrast to the regular colors as it's easy to miss it otherwise. I'll go ahead and change it to `#333`.

**Comment by Mottie** [comment]
Ok, add it to an already defined `#333` entry please. There are two, make sure to add it to the one with the `!important` flag.

**Comment by HerrHulaHoop** [comment]
Done 👍

**Comment by Mottie** [comment]
Thanks!

**Pull request merged**
