### PR TITLE
Fixed Wikipedia:Contents pages + added color to Current Events + a few lint errors I made

### PR DESCRIPTION
**Pull request by saya-rbt**
This is a continuation of #191. It has been merged, but quickly after, I realized that the Contents pages were also broken, so I went ahead and fixed them.

I also used it to add some color to the Current Events titles, to make them easier to distinguish and the page overall more pleasant to read. (@the-j0k3r this is for you :stuck_out_tongue:)

Lastly, when running `npm test`, I realized there were a few lint errors I made that got merged upstream, so I fixed my mistakes and included them in this commit as well.

Please let me know what you think!

### CODE REVIEW

**Comment by the-j0k3r** [comment]
Problem is that you are ignoring the colors.

What is blue by default should remain blue and what is green should remain green. This includes the backgrounds not just the headers.

So now what was blue is now green what was green bg is all gray and nothing matches the default styling.

**Comment by saya-rbt** [comment]
Ah I see, sorry about that.

It's fine, I'll fix it in the next few days again, no worries!

Sorry for not getting it earlier, I'll do it properly this time, just give me some time as I am quite busy these days :)

**Comment by the-j0k3r** [comment]
> Sorry for not getting it earlier, I'll do it properly this time, just give me some time as I am quite busy these days :)

Thanks and dont worry about it, it was just loud noises from the time I spent countless hours time fixing this.
Im glad someone even cares to fix it no matter what.

Thanks again.

**Comment by AfroThundr3007730** [comment]
> > Sorry for not getting it earlier, I'll do it properly this time, just give me some time as I am quite busy these days :)
> 
> Thanks and dont worry about it, it was just loud noises from the time I spent countless hours time fixing this. Im glad someone even cares to fix it no matter what.
> 
> Thanks again.

I've been super busy these days, but I'm still watching this repo. I'll fix any breaking changes as I find them. Thanks for keeping up with the reviews though.

**Comment by AfroThundr3007730** [comment]
@saya-rbt Were you still planning to update the color selections? We can merge it once that's done.

**Comment by saya-rbt** [comment]
@AfroThundr3007730 yes, I would like to do so. I'm sorry I haven't been able to do so before, I've been really busy these days.

Depending on my current workload, I might be able to do it tomorrow or on Saturday. I should be able to be done within the next week ultimately, but this is a very temporary ETA as my workload is quite unpredictable.

If you're fine with me getting done with it around next week, I'll do it. Otherwise, if you would like to merge these (unfinished) changes, please go ahead.

**Comment by AfroThundr3007730** [comment]
That's cool, no rush here.

**Pull request closed without merging**
