### PR TITLE
wikiversity proofs

### PR DESCRIPTION
**Pull request by anastygnome**
Edit the theme so that  wikiversity proof do not appear as white-on-white.

### CODE REVIEW

**Comment by the-j0k3r** [comment]
@anastygnome hello and thanks for reaching out with this contribution.

Could you post a link to the specific page please?

**Comment by anastygnome** [comment]
I know it's in french but 
https://fr.wikiversity.org/wiki/Fonction_d%C3%A9riv%C3%A9e/Extremum_local

**Comment by anastygnome** [comment]
after the change 
image
before the change
image

**Comment by the-j0k3r** [comment]
I cant actually see what you see but looks ok, even if yellow  should be brown, not gray and we arealy have such rules so no new ones need to be created.

**Pull request closed without merging**
