### PR TITLE
Fix survey background color

### PR DESCRIPTION
**Pull request by TotalCaesar659**
Sometimes there are goes survey: "Does this page load fast enough?" "Yes/Not sure/No". For more information, see this survey's [privacy statement](https://foundation.wikimedia.org/wiki/Performance_Perception_Survey_Privacy_Statement).

### CODE REVIEW

**Comment by the-j0k3r** [comment]
Thanks for PR.

2 comments.

1) if this is in ru site only why use a general section?
2) why add a new rule instead of adding the selector to an existing rule with same property

**Comment by TotalCaesar659** [comment]
1. I have a doubt that this survey is only for RU zone.
2. I don't know where would be ф proper proper place for this, so you can tell me. And separate section would be faster to find if there are any problems.

**Comment by TotalCaesar659** [comment]
> 1. I have a doubt that this survey is only for RU zone.
> 2. I don't know where would be a proper proper place for this, so you can tell me. And separate section would be faster to find if there are any problems.

**Comment by the-j0k3r** [comment]
We dont support blogs on this style. Just FYI

**Comment by TotalCaesar659** [comment]
I didn't ask support for this blog and don't understand why you thought about it. I gave that URL just for proof that the survey is not for RU zone - there is a picture under "_The micro survey simply asks users on Wikipedia articles, in their own language, if they think that the current page loaded fast enough:_"

**Comment by the-j0k3r** [comment]
> I didn't ask support for this blog and don't understand why you thought about it

Cause no other links pop this up for me, have never seen it

**Pull request merged**
