### PR TITLE
Logo images: Darken globe, brighten text and update README

### PR DESCRIPTION
**Pull request by Aced14**
These changes darken the logo images' globes to retain more detail and partially-invert the logos' text colour to match the theme's light grey font colour (#9a9a9a).

A reference in the README about it being impractical to adjust the text in the logo images was also removed.

Closes #29.

**Screenshots (outdated - see https://github.com/StylishThemes/Wikipedia-Dark/pull/30#issuecomment-354706522 for updated after screenshots)...**

**Main index page - before:**
index-before

**Main index page - after:**
index-after

**English index page - before:**
index-en-before

**English index page - after:**
index-en-after

### CODE REVIEW

**Comment by Aced14** [comment]
Btw just to throw another idea out there... here's what the globe would look like if its brightness was set to 60.5%. It'd look more consistent with the theme's font colour and would retain much more detail than the 33% inversion filter that the master branch is currently using.

@Mottie Thoughts? I could update this PR to make the globe look like that if you're cool with it.

**Screenshots...**

**Main index page - after (if the globe's brightness was set to 60.5%):**
index-after-globe-brightness-60 5

**English index page - after (if the globe's brightness was set to 60.5%):**
index-en-after-globe-brightness-60 5

**Comment by Mottie** [comment]
Yes, go for it.

**Comment by Aced14** [comment]
@Mottie Updated :)! Also revised this PR's title and OP.

**Comment by Aced14** [comment]
@Mottie Just wondering if there's anything holding back this PR from being merged in? Its changes currently look like the screenshots from https://github.com/StylishThemes/Wikipedia-Dark/pull/30#issuecomment-354706522.

**Comment by Mottie** [comment]
Oh! Sorry, I totally forgot. I'll take a look

**Pull request merged**
