### PR TITLE
Use dark background for table header

### PR DESCRIPTION
**Pull request by Poorchop**
[Example](https://en.wikipedia.org/wiki/Kobo_eReader#Market_share)

### CODE REVIEW

**Comment by Mottie** [comment]
Thanks! Now how about fixing [this one](https://en.wikipedia.org/wiki/List_of_The_Simpsons_episodes)? :wink: 

Just kidding LOL

**Comment by Poorchop** [comment]
I'm guessing there's no general fix for that without using JavaScript but why not just use the background colors as selectors as you have already done for a few other rules? Hopefully that color palette is reused in other episode list wikis so you wouldn't have to make a million custom rules.

**Comment by Mottie** [comment]
It's not reused, that's the problem.

When people add color to wiki tables, they add it to the style directly like this:

```
{| class="wikitable plainrowheaders" style="margin: auto; width: 100%"
|-
!! style="background:#FBF201; color:#000; text-align:center;"|Title
!! style="background:#FBF201; color:#000; text-align:center;"|Directed by
!! style="background:#FBF201; color:#000; text-align:center;"|Screenplay by
!! style="background:#FBF201; color:#000; text-align:center;"|Release date<br>(U.S.)
!! style="background:#FBF201; color:#000; text-align:center;"|Release date<br>(International)
{{Episode list
|RTitle          = ''[[The Simpsons Movie]]''
|DirectedBy      = [[David Silverman (animator)|David Silverman]]
|WrittenBy       = [[James L. Brooks]], [[Matt Groening]], [[Al Jean]], [[Ian Maxtone-Graham]],<br />[[George Meyer]], [[David Mirkin]], [[Mike Reiss]], [[Mike Scully]], [[Matt Selman]], [[John Swartzwelder]] and [[Jon Vitti]]
|OriginalAirDate = {{Start date|2007|7|27}}
|AltDate         = {{Start date|2007|7|26}}
}}
|}
```

**Comment by Mottie** [comment]
Find any other TV show and look at the episodes list...

Here is [The Arrow](https://en.wikipedia.org/wiki/List_of_Arrow_episodes). All the table headers are different shades of green.

**Pull request merged**
