### PR TITLE
Fix review notice

### PR DESCRIPTION
**Pull request by TotalCaesar659**
Text of review notices is almost invisible, e.g. https://ru.wikipedia.org/wiki/Чайф ("The current article version hasn't been reviewed yet by skilled contributors and may differ from one checked 12 March 2019; 1 edit has to be checked.").
Before

After

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @TotalCaesar659!

Thanks for your contribution! Please move the selector up to [this block](https://github.com/StylishThemes/Wikipedia-Dark/blob/master/wikipedia-dark.user.css#L77-L83) (to the end of line 81). Our convention is to combine common definitions and to add all new selectors to end of the list. We may not always follow this rule strictly, but it keep from having way too many repeated definitions.

Also note that there are two different definitions for `color: #9a9a9a`; one with and one without an `!important` flag.

**Comment by TotalCaesar659** [comment]
Fixed, and what's the difference between them?

**Comment by the-j0k3r** [comment]
> Fixed, and what's the difference between them?

The difference is instead of having two rules with same attributes we only have one. Basically what @mottie said.

**Comment by Mottie** [comment]
I think they were asking why there is a color definition with and without an important flag. The one without an important flag is applied to general elements, like all table cells; this allows the color of the cell to fit our dark style and not override any inline style color settings on table cells that have a background color.

**Comment by the-j0k3r** [comment]
Thank you for this contribution =) I manually added your fix due to a conflict in PR, it was faster this way.

**Pull request closed without merging**
